/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tollier;

import config.connectDB;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mendo
 */
public class TollierDB extends javax.swing.JFrame {

    /**
     * Creates new form TollierDB
     */
    public TollierDB() {
        initComponents();
        displayData();
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    public void displayData() {
    try {
        connectDB dbc = new connectDB();
        
        // Select only the specific columns from tbl_user
        String query = "SELECT a_id, a_name, a_rate, a_location, a_status FROM area_tbl";
        ResultSet rs = dbc.getData(query);
        
        // Use DbUtils to set the result set to the table
        overview.setModel(DbUtils.resultSetToTableModel(rs));

        // Change column titles
        overview.getColumnModel().getColumn(0).setHeaderValue("ID");
        overview.getColumnModel().getColumn(1).setHeaderValue("Name");
        overview.getColumnModel().getColumn(2).setHeaderValue("Rate");
        overview.getColumnModel().getColumn(3).setHeaderValue("Location");
        overview.getColumnModel().getColumn(4).setHeaderValue("Status");
        
        
        // Refresh the table to apply the new headers
        overview.getTableHeader().repaint();
        
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        none = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        admin1 = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        admin2 = new javax.swing.JLabel();
        transaction = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        park = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(173, 216, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        none.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        none.setForeground(new java.awt.Color(102, 102, 102));
        none.setText("TOLLIER");
        jPanel2.add(none, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 130, -1, -1));

        dashboard.setBackground(new java.awt.Color(173, 216, 230));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin1.setText("DASHBOARD");
        dashboard.add(admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 8, -1, -1));

        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 40));

        account.setBackground(new java.awt.Color(173, 216, 230));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin2.setText("ACCOUNT");
        account.add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 7, -1, -1));

        jPanel2.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        transaction.setBackground(new java.awt.Color(173, 216, 230));
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionMouseExited(evt);
            }
        });
        transaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin.setText("TRANSACTIONS");
        transaction.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 8, -1, -1));

        jPanel2.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 470));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("TOLLIER DASHBOARD");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(173, 216, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(overview);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 220));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 650, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Parking Areas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        park.setBackground(new java.awt.Color(173, 216, 230));
        park.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parkMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                parkMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                parkMouseExited(evt);
            }
        });
        park.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(173, 216, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        park.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("PARK");
        park.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(park, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
          
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        dashboard.setBackground(lightGray);
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setBackground(lightBlue);
    }//GEN-LAST:event_dashboardMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
       Account go = new Account();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
       account.setBackground(lightGray);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(lightBlue);
    }//GEN-LAST:event_accountMouseExited

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked
         Transactions go = new Transactions();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_transactionMouseClicked

    private void transactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseEntered
        transaction.setBackground(lightGray);
    }//GEN-LAST:event_transactionMouseEntered

    private void transactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseExited
        transaction.setBackground(lightBlue);
    }//GEN-LAST:event_transactionMouseExited

    private void parkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkMouseClicked
         int selectedRow = overview.getSelectedRow(); 

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a parking area first.", "No Selection", JOptionPane.WARNING_MESSAGE);
        return; 
    }

    
    String status = overview.getValueAt(selectedRow, 4).toString();

    if (status.equalsIgnoreCase("Occupied")) {
        JOptionPane.showMessageDialog(this, "Selected parking area is already occupied.", "Unavailable", JOptionPane.WARNING_MESSAGE);
        return;
    }

    
    String areaId = overview.getValueAt(selectedRow, 0).toString(); 

    
    AddPark parkForm = new AddPark(areaId);
    parkForm.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_parkMouseClicked

    private void parkMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkMouseEntered
        park.setBackground(lightGray);
    }//GEN-LAST:event_parkMouseEntered

    private void parkMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parkMouseExited
        park.setBackground(lightBlue);
    }//GEN-LAST:event_parkMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TollierDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TollierDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TollierDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TollierDB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TollierDB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel admin1;
    private javax.swing.JLabel admin2;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel none;
    private javax.swing.JTable overview;
    private javax.swing.JPanel park;
    private javax.swing.JPanel transaction;
    // End of variables declaration//GEN-END:variables
}
