/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.awt.Color;
import Tollier.TollierDB;
import Admin.AdminDB;
import Forgotpass.ForgotPass;
import config.DBLogger;
import config.connectDB;
import config.hasher;
import config.session;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author mendo
 */
public class LoginPanel extends javax.swing.JFrame {
public static int loggedInUserId;
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    
    public String[] loginAcc(String email, String password) {
    connectDB con = new connectDB ();

    try {
        String query = "SELECT u_hashpw, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim());
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            String storedHashedPassword = resultSet.getString("u_hashpw");
            String hashedInputPassword = hasher.hashPassword(password); // Hash input password

            // Compare hashed input with stored hash
            if (hashedInputPassword.equals(storedHashedPassword)) {
                return new String[]{resultSet.getString("u_type").trim(), resultSet.getString("u_status").trim()};
            }
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if login fails
}


    
    public String[] getUserDetails(String email) {
    connectDB con = new connectDB();
    try {
        String query = "SELECT u_id, u_firstname, u_lastname, u_email, u_contactnumber, u_type, u_status FROM tbl_user WHERE u_email = ?";
        PreparedStatement pstmt = con.getConnection().prepareStatement(query);
        pstmt.setString(1, email.trim()); // Set email as the query parameter
        ResultSet resultSet = pstmt.executeQuery();

        if (resultSet.next()) {
            return new String[]{
                resultSet.getString("u_id").trim(),
                resultSet.getString("u_firstname").trim(),
                resultSet.getString("u_lastname").trim(),
                resultSet.getString("u_email").trim(),
                resultSet.getString("u_contactnumber").trim(),
                resultSet.getString("u_type").trim(),
                resultSet.getString("u_status").trim()
            };
        }
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    return null; // Return null if no user is found
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        requiredpass = new javax.swing.JLabel();
        requireduser = new javax.swing.JLabel();
        login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        forgot = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        registerbutton = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Screenshot 2025-06-01 002256.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 380));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(173, 216, 230));
        jLabel3.setText("Login");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        username.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                usernameFocusLost(evt);
            }
        });
        jPanel3.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 230, 40));

        password.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                passwordFocusLost(evt);
            }
        });
        jPanel3.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 230, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Email");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("Password");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel3.add(requiredpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 230, 10));
        jPanel3.add(requireduser, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 230, 10));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 310, 150));

        login.setBackground(new java.awt.Color(173, 216, 230));
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });
        login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Login");
        login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 1, -1, -1));

        jPanel1.add(login, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        forgot.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        forgot.setText("Forgot Password");
        forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotMouseClicked(evt);
            }
        });
        jPanel1.add(forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Don't have an account?");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        registerbutton.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        registerbutton.setForeground(new java.awt.Color(0, 153, 153));
        registerbutton.setText(" Register here");
        registerbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbuttonMouseClicked(evt);
            }
        });
        jPanel1.add(registerbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_usernameFocusLost
       
    }//GEN-LAST:event_usernameFocusLost

    private void passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordFocusLost
        
    }//GEN-LAST:event_passwordFocusLost

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
      String user = username.getText().trim();
    String pass = password.getText().trim();

    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username and/or password cannot be empty.", "Login Error", JOptionPane.ERROR_MESSAGE);
        username.requestFocus();
        return;
    }

    try {
        // Directly use the entered username and password without hashing
        String[] loginData = loginAcc(user, pass);

        if (loginData == null) {
            // Failed login attempt
            DBLogger.log(user, "Failed login attempt");  // Log failed attempt
            JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            password.requestFocus();
            return;
        }

        String[] userDetails = getUserDetails(user);

        String userID = userDetails[0];
        String firstName = userDetails[1];
        String lastName = userDetails[2];
        String email = userDetails[3];
        String contactNumber = userDetails[4];
        String accType = loginData[0];
        String accStatus = loginData[1];

        if (!"active".equalsIgnoreCase(accStatus)) {
            // Account is not active
            DBLogger.log(user, "Inactive account login attempt");  // Log attempt with inactive account
            JOptionPane.showMessageDialog(this, "Your account is still pending. Please contact the administrator.", "Login Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        session sess = session.getInstance();
        sess.setU_id(userID);
        sess.setUsername(user);
        sess.setFirstName(firstName);
        sess.setLastName(lastName);
        sess.setEmail(email);
        sess.setContact(contactNumber);
        sess.setAcc_type(accType);
        sess.setAcc_status(accStatus);

        if (accType != null) {
            if ("Admin".equalsIgnoreCase(accType)) {
                DBLogger.log(user, "Admin logged in");  // Log successful login for Admin
                new AdminDB().setVisible(true);
            } else if ("Tollier".equalsIgnoreCase(accType)) {
                DBLogger.log(user, "Tollier logged in");  // Log successful login for Employee
                new TollierDB().setVisible(true);
            } else {
                // Invalid user type
                DBLogger.log(user, "Unknown user type login attempt");  // Log unknown user type attempt
                JOptionPane.showMessageDialog(this, "Unknown user type!", "Login Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            this.dispose(); // Close login window
        } else {
            // Invalid login credentials
            DBLogger.log(user, "Incorrect login credentials");  // Log incorrect credentials attempt
            JOptionPane.showMessageDialog(this, "Incorrect username or password.", "Login Error", JOptionPane.ERROR_MESSAGE);
            password.requestFocus();
        }

    } catch (Exception e) {
        // Log error during login
        DBLogger.log(user, "Error during login: " + e.getMessage());  // Log error
        JOptionPane.showMessageDialog(this, "Error during login: " + e.getMessage(), "Login Error", JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }

    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
        login.setBackground(lightGray);
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
        login.setBackground(lightBlue);
    }//GEN-LAST:event_loginMouseExited

    private void forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotMouseClicked
        ForgotPass reg = new ForgotPass();

        reg.setVisible(true);
        this.dispose();   
    }//GEN-LAST:event_forgotMouseClicked

    private void registerbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbuttonMouseClicked
        SignupPanel reg = new SignupPanel();

        reg.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_registerbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel forgot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel login;
    private javax.swing.JPasswordField password;
    private javax.swing.JLabel registerbutton;
    private javax.swing.JLabel requiredpass;
    private javax.swing.JLabel requireduser;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
