/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import config.DBLogger;
import config.connectDB;
import config.session;
import java.awt.Color;
import java.awt.Frame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mendo
 */
public class EditArea extends javax.swing.JFrame {

    /**
     * Creates new form EditArea
     */
   public EditArea(String id, String name, double rate, String location) {
    initComponents();
    idfieldtext.setText(id);
    aname.setText(name);
    arate.setText(String.valueOf(rate));
    alocation.setText(location);
}
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
     private boolean emailExists(String email) {

        connectDB con = new connectDB();

        try {
            String query = "SELECT * FROM area_tbl WHERE a_id = ?";
            PreparedStatement pstmt = con.getConnection().prepareStatement(query);
            pstmt.setString(1, email.trim());
            ResultSet resultSet = pstmt.executeQuery();

            if (resultSet.next()) {

                return true;
            }

        } catch (SQLException ex) {
            System.out.println("" + ex);

        }

        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aname = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        emailtext = new javax.swing.JLabel();
        alocation = new javax.swing.JTextField();
        arate = new javax.swing.JTextField();
        lastnametext = new javax.swing.JLabel();
        create = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        idfieldtext = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("EDIT AREA");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout (2).png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        aname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        aname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                anameFocusLost(evt);
            }
        });
        aname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anameActionPerformed(evt);
            }
        });
        jPanel2.add(aname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 196, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Name");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        emailtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        emailtext.setText("Location");
        jPanel2.add(emailtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 60, -1));

        alocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        alocation.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                alocationFocusLost(evt);
            }
        });
        alocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alocationActionPerformed(evt);
            }
        });
        jPanel2.add(alocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 196, 30));

        arate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                arateFocusLost(evt);
            }
        });
        arate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arateActionPerformed(evt);
            }
        });
        jPanel2.add(arate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 196, 30));

        lastnametext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lastnametext.setText("Rate");
        jPanel2.add(lastnametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, -1));

        create.setBackground(new java.awt.Color(173, 216, 230));
        create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createMouseExited(evt);
            }
        });
        create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(173, 216, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        create.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("EDIT");
        create.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        jPanel2.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 100, 30));

        idfieldtext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        idfieldtext.setText("ID:");
        jPanel2.add(idfieldtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 60, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("ID:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 670, 390));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
          for (Frame f : Frame.getFrames()) {
    if (f instanceof Areas) {
        f.setVisible(true);
        this.dispose();
        return;
    }
}
        Areas go = new Areas();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void anameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_anameFocusLost

    }//GEN-LAST:event_anameFocusLost

    private void anameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anameActionPerformed

    private void alocationFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_alocationFocusLost

    }//GEN-LAST:event_alocationFocusLost

    private void alocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alocationActionPerformed

    }//GEN-LAST:event_alocationActionPerformed

    private void arateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_arateFocusLost

    }//GEN-LAST:event_arateFocusLost

    private void arateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arateActionPerformed

    private void createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseClicked
       connectDB con = new connectDB();

con.updateData("UPDATE area_tbl SET a_name = '" + aname.getText() + 
    "', a_rate = '" + arate.getText() + 
    "', a_location = '" + alocation.getText() + 
    "' WHERE a_id = '" + idfieldtext.getText() + "'");

JOptionPane.showMessageDialog(this, "Area Updated Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

Areas acc = new Areas();
acc.setVisible(true);
this.dispose();
    }//GEN-LAST:event_createMouseClicked

    private void createMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseEntered
        create.setBackground(lightGray);
    }//GEN-LAST:event_createMouseEntered

    private void createMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createMouseExited
        create.setBackground(lightBlue);
    }//GEN-LAST:event_createMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditArea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            String id       = null;
            String name     = null;
            int    rate     = 0;
            String location = null;

    EditArea eda = new EditArea(id, name, rate, location);
    eda.setVisible(true);
}
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alocation;
    private javax.swing.JTextField aname;
    private javax.swing.JTextField arate;
    private javax.swing.JPanel create;
    private javax.swing.JLabel emailtext;
    private javax.swing.JLabel idfieldtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lastnametext;
    // End of variables declaration//GEN-END:variables
}
