/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import Tollier.*;
import Forgotpass.*;
import static Tollier.SecretQuestion.hashSecretAnswer;
import config.connectDB;
import java.awt.Color;
import java.awt.Font;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author mendo
 */
public class SecretQuestion extends javax.swing.JFrame {

    /**
     * Creates new form SecretQuestion
     */
    public SecretQuestion() {
        initComponents();
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
   public static String hashSecretAnswer(String input) {
    try {
        MessageDigest md = MessageDigest.getInstance("SHA-256");
        byte[] hashBytes = md.digest(input.getBytes(StandardCharsets.UTF_8));
        StringBuilder sb = new StringBuilder();
        for (byte b : hashBytes) {
            sb.append(String.format("%02x", b));
        }
        return sb.toString();
    } catch (NoSuchAlgorithmException e) {
        throw new RuntimeException("Error hashing answer", e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        questiontext = new javax.swing.JLabel();
        question = new javax.swing.JComboBox<>();
        answer = new javax.swing.JPasswordField();
        answertext = new javax.swing.JLabel();
        answerrequired = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        edit = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        questiontext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        questiontext.setText("Question");
        jPanel2.add(questiontext, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Choose Questions)", "What is your mother's maiden name?", "What was the name of your first pet?", "What was the name of your elementary school?", "What is your favorite color?", "What city were you born in?", "" }));
        question.setOpaque(false);
        question.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                questionFocusLost(evt);
            }
        });
        question.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionActionPerformed(evt);
            }
        });
        jPanel2.add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 200, 40));

        answer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                answerFocusLost(evt);
            }
        });
        answer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                answerActionPerformed(evt);
            }
        });
        jPanel2.add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 30));

        answertext.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        answertext.setText("Answer");
        jPanel2.add(answertext, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        answerrequired.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jPanel2.add(answerrequired, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 10));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("CHOOSE A QUESTION");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 10, -1, -1));

        cancel.setBackground(new java.awt.Color(173, 216, 230));
        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(173, 216, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        cancel.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("CANCEL");
        cancel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel2.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 100, 30));

        edit.setBackground(new java.awt.Color(173, 216, 230));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editMouseExited(evt);
            }
        });
        edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(173, 216, 230));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        edit.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("EDIT");
        edit.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        jPanel2.add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 100, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 320, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void questionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_questionFocusLost

    }//GEN-LAST:event_questionFocusLost

    private void questionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionActionPerformed
        String selectedQuestion = question.getSelectedItem().toString();

        if (selectedQuestion.equals("Select a question")) {
            question.setForeground(Color.RED);
            JOptionPane.showMessageDialog(null, "Please select a security question.", "Validation Error", JOptionPane.WARNING_MESSAGE);
        } else {
            question.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_questionActionPerformed

    private void answerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_answerFocusLost
        Font smallFont = new Font("Arial", Font.PLAIN, 10);
        answer.setFont(smallFont);
        answerrequired.setFont(smallFont);

        // Get the password as a String
        String password1 = new String(answer.getPassword());

        if (password1.isEmpty()) {
            answer.setForeground(Color.RED);
            answerrequired.setText("Answer is required");
            answerrequired.setForeground(Color.RED);
        } else {
            answer.setForeground(Color.BLACK);
            answerrequired.setText("");
        }

        answer.repaint();
    }//GEN-LAST:event_answerFocusLost

    private void answerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_answerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_answerActionPerformed

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
         Account go = new Account();
         go.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
        cancel.setBackground(lightGray);
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
        cancel.setBackground(lightBlue);
    }//GEN-LAST:event_cancelMouseExited

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
       if (answer == null || answer.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(
            null,
            "Secret answer cannot be empty. Please provide an answer.",
            "Validation Error",
            JOptionPane.WARNING_MESSAGE
        );
    } else {
        String sql = "UPDATE tbl_user SET u_question = ?, u_answer = ? WHERE u_email = ?";
        connectDB dbc = new connectDB();

        try (Connection conn = dbc.getConnection();
             PreparedStatement pst = conn.prepareStatement(sql)) {

            String ques = question.getSelectedItem().toString();
            String ans = answer.getText().trim();
            String hashedAns = hashSecretAnswer(ans); 
            String email = connectDB.loggedInEmail;

            pst.setString(1, ques);
            pst.setString(2, hashedAns); 
            pst.setString(3, email);

            int rows = pst.executeUpdate();

            if (rows > 0) {
                JOptionPane.showMessageDialog(
                    null,
                    "Secret question and answer updated successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
                );
            } else {
                JOptionPane.showMessageDialog(
                    null,
                    "Failed to update secret question and answer.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
                );
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(
                null,
                "Database error: " + ex.getMessage(),
                "SQL Exception",
                JOptionPane.ERROR_MESSAGE
            );
        }

        Account acb = new Account();
        this.dispose();
        acb.setVisible(true);
    }
    }//GEN-LAST:event_editMouseClicked

    private void editMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseEntered
        edit.setBackground(lightGray);
    }//GEN-LAST:event_editMouseEntered

    private void editMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseExited
       edit.setBackground(lightBlue);
    }//GEN-LAST:event_editMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecretQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecretQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecretQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecretQuestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SecretQuestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField answer;
    private javax.swing.JLabel answerrequired;
    private javax.swing.JLabel answertext;
    private javax.swing.JPanel cancel;
    private javax.swing.JPanel edit;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> question;
    private javax.swing.JLabel questiontext;
    // End of variables declaration//GEN-END:variables
}
