/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import config.connectDB;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.print.PrinterException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author mendo
 */
public class Transactions extends javax.swing.JFrame {

    /**
     * Creates new form Transactions
     */
    public Transactions() {
        initComponents();
        displayData();
    }
    Color lightGray = new Color(211, 211, 211);
    Color lightBlue = new Color(173, 216, 230);
    public void displayData() {
    try {
        connectDB dbc = new connectDB();
        
        // Select specific columns from transactions table
        String query = "SELECT t_id, a_id, customer_name, car_plate, contact_number, hours, total_due, transaction_time, status FROM transactions";
        ResultSet rs = dbc.getData(query);
        
        // Set the result set to the table model using DbUtils
        overview.setModel(DbUtils.resultSetToTableModel(rs));
        
        // Change column titles according to the query columns
        overview.getColumnModel().getColumn(0).setHeaderValue("Transaction ID");      // t_id
        overview.getColumnModel().getColumn(1).setHeaderValue("Area ID");            // a_id
        overview.getColumnModel().getColumn(2).setHeaderValue("Customer Name");       // customer_name
        overview.getColumnModel().getColumn(3).setHeaderValue("Car Plate");           // car_plate
        overview.getColumnModel().getColumn(4).setHeaderValue("Contact Number");      // contact_number
        overview.getColumnModel().getColumn(5).setHeaderValue("Hours");               // hours
        overview.getColumnModel().getColumn(6).setHeaderValue("Total Due");           // total_due
        overview.getColumnModel().getColumn(7).setHeaderValue("Transaction Time");    // transaction_time
        overview.getColumnModel().getColumn(8).setHeaderValue("Status");              // status
        
        // Refresh the table headers to display the new names
        overview.getTableHeader().repaint();
        
    } catch (SQLException ex) {
        System.out.println("Errors: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        adminname = new javax.swing.JLabel();
        account = new javax.swing.JPanel();
        admin = new javax.swing.JLabel();
        dashboard = new javax.swing.JPanel();
        admin1 = new javax.swing.JLabel();
        areas = new javax.swing.JPanel();
        admin3 = new javax.swing.JLabel();
        transaction = new javax.swing.JPanel();
        admin4 = new javax.swing.JLabel();
        users = new javax.swing.JPanel();
        admin2 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        overview = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        reciept = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        paid = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        refresh = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(173, 216, 230));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminname.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        adminname.setForeground(new java.awt.Color(102, 102, 102));
        adminname.setText("ADMIN");
        jPanel2.add(adminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 130, -1, -1));

        account.setBackground(new java.awt.Color(173, 216, 230));
        account.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accountMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                accountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                accountMouseExited(evt);
            }
        });
        account.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin.setText("ACCOUNT");
        account.add(admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 7, -1, -1));

        jPanel2.add(account, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 170, 40));

        dashboard.setBackground(new java.awt.Color(173, 216, 230));
        dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardMouseExited(evt);
            }
        });
        dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin1.setText("DASHBOARD");
        dashboard.add(admin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 8, -1, -1));

        jPanel2.add(dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 170, 40));

        areas.setBackground(new java.awt.Color(173, 216, 230));
        areas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                areasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                areasMouseExited(evt);
            }
        });
        areas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin3.setText("AREAS");
        areas.add(admin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 7, -1, -1));

        jPanel2.add(areas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 170, 40));

        transaction.setBackground(new java.awt.Color(173, 216, 230));
        transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transactionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transactionMouseExited(evt);
            }
        });
        transaction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin4.setText("TRANSACTIONS");
        transaction.add(admin4, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 8, -1, -1));

        jPanel2.add(transaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 170, 40));

        users.setBackground(new java.awt.Color(173, 216, 230));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usersMouseExited(evt);
            }
        });
        users.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin2.setText("USERS");
        users.add(admin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 7, -1, -1));

        jPanel2.add(users, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 170, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 470));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("TRANSACTIONS");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, -1, -1));

        jPanel4.setBackground(new java.awt.Color(173, 216, 230));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(overview);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 630, 220));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 650, 240));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Transaction Records");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, -1, -1));

        reciept.setBackground(new java.awt.Color(173, 216, 230));
        reciept.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recieptMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                recieptMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                recieptMouseExited(evt);
            }
        });
        reciept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(173, 216, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        reciept.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("RECIEPT");
        reciept.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jPanel1.add(reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 100, 30));

        paid.setBackground(new java.awt.Color(173, 216, 230));
        paid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paidMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paidMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                paidMouseExited(evt);
            }
        });
        paid.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(173, 216, 230));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        paid.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("PAID");
        paid.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 10, -1, -1));

        jPanel1.add(paid, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 100, 30));

        refresh.setBackground(new java.awt.Color(173, 216, 230));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                refreshMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                refreshMouseExited(evt);
            }
        });
        refresh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(173, 216, 230));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        refresh.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 100, 40));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("REFRESH");
        refresh.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 838, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void recieptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recieptMouseClicked
     int selectedRow = overview.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a transaction from the table.");
        return;
    }

    Object statusObj = overview.getValueAt(selectedRow, 8);
    String status = statusObj.toString().trim().toLowerCase();

    if (status.equals("pending")) {
        JOptionPane.showMessageDialog(null, "Cannot generate receipt for pending transactions.", "Action Blocked", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Object transactionID = overview.getValueAt(selectedRow, 0);
    Object areaID = overview.getValueAt(selectedRow, 1);
    Object customerName = overview.getValueAt(selectedRow, 2);
    Object carPlate = overview.getValueAt(selectedRow, 3);
    Object contactNumber = overview.getValueAt(selectedRow, 4);
    Object hours = overview.getValueAt(selectedRow, 5);
    Object totalDue = overview.getValueAt(selectedRow, 6);
    Object transactionTime = overview.getValueAt(selectedRow, 7);

    String receipt = String.format(
        "************ iPark Parking System ************%n" +
        "             Welcome and Thank You!           %n" +
        "----------------------------------------------%n" +
        "Transaction ID  : %s%n" +
        "Area ID         : %s%n" +
        "Customer Name   : %s%n" +
        "Car Plate       : %s%n" +
        "Contact Number  : %s%n" +
        "Hours Parked    : %s%n" +
        "Total Due       : ₱%s%n" +
        "Transaction Time: %s%n" +
        "Status          : %s%n" +
        "----------------------------------------------%n" +
        "Thank you for parking with iPark!%n" +
        "Have a great day!%n",
        transactionID, areaID, customerName, carPlate, contactNumber, hours, totalDue, transactionTime, statusObj
    );

    JTextArea textArea = new JTextArea(receipt);
    textArea.setEditable(false);
    textArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
    JScrollPane scrollPane = new JScrollPane(textArea);
    scrollPane.setPreferredSize(new Dimension(400, 300));

    int option = JOptionPane.showOptionDialog(
        null, scrollPane, "Receipt",
        JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE,
        null, new String[]{"Print", "Close"}, "Print"
    );

    if (option == JOptionPane.YES_OPTION) {
        try {
            boolean complete = textArea.print();
            if (complete) {
                JOptionPane.showMessageDialog(null, "Receipt printed successfully.");
            } else {
                JOptionPane.showMessageDialog(null, "Printing was cancelled.");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, "Printing failed: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_recieptMouseClicked

    private void recieptMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recieptMouseEntered
        reciept.setBackground(lightGray);
    }//GEN-LAST:event_recieptMouseEntered

    private void recieptMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recieptMouseExited
        reciept.setBackground(lightBlue);
    }//GEN-LAST:event_recieptMouseExited

    private void paidMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidMouseClicked
         int selectedRow = overview.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(null, "Please select a transaction to mark as paid.");
        return;
    }

    Object transactionID = overview.getValueAt(selectedRow, 0); // Assuming ID is in column 0

    int confirm = JOptionPane.showConfirmDialog(null, "Mark this transaction as PAID?", "Confirm", JOptionPane.YES_NO_OPTION);
    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        connectDB db = new connectDB();
        String updateQuery = "UPDATE transactions SET status = 'Paid' WHERE t_id = ?";
        PreparedStatement pst = db.connect.prepareStatement(updateQuery);
        pst.setObject(1, transactionID);

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Transaction marked as PAID.");
            // Optionally reload the table here
        } else {
            JOptionPane.showMessageDialog(null, "Failed to update transaction status.");
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_paidMouseClicked

    private void paidMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidMouseEntered
        paid.setBackground(lightGray);
    }//GEN-LAST:event_paidMouseEntered

    private void paidMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidMouseExited
        paid.setBackground(lightBlue);
    }//GEN-LAST:event_paidMouseExited

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
        displayData();
    }//GEN-LAST:event_refreshMouseClicked

    private void refreshMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseEntered
        refresh.setBackground(lightGray);
    }//GEN-LAST:event_refreshMouseEntered

    private void refreshMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseExited
        refresh.setBackground(lightBlue);
    }//GEN-LAST:event_refreshMouseExited

    private void accountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseClicked
           JDialog loadingDialog = new JDialog(this, "Loading", true);
    JLabel loadingLabel = new JLabel("Loading, please wait...", SwingConstants.CENTER);
    loadingDialog.add(loadingLabel);
    loadingDialog.setSize(200, 100);
    loadingDialog.setLocationRelativeTo(this);
    loadingDialog.setUndecorated(true);
    loadingDialog.setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);

   
    SwingUtilities.invokeLater(() -> loadingDialog.setVisible(true));

    
    new Thread(() -> {
        try {
            Thread.sleep(1000); 
        } catch (InterruptedException e) {
            e.printStackTrace();
        }

       
        loadingDialog.dispose();

        SwingUtilities.invokeLater(() -> {
            Account go = new Account();
            go.setVisible(true);
            this.dispose();
        });
    }).start();
    }//GEN-LAST:event_accountMouseClicked

    private void accountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseEntered
        account.setBackground(lightGray);
    }//GEN-LAST:event_accountMouseEntered

    private void accountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accountMouseExited
        account.setBackground(lightBlue);
    }//GEN-LAST:event_accountMouseExited

    private void dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseClicked
        AdminDB go = new AdminDB();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboardMouseClicked

    private void dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseEntered
        dashboard.setBackground(lightGray);
    }//GEN-LAST:event_dashboardMouseEntered

    private void dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMouseExited
        dashboard.setBackground(lightBlue);
    }//GEN-LAST:event_dashboardMouseExited

    private void areasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasMouseClicked
        Areas go = new Areas();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_areasMouseClicked

    private void areasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasMouseEntered
        areas.setBackground(lightGray);
    }//GEN-LAST:event_areasMouseEntered

    private void areasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areasMouseExited
        areas.setBackground(lightBlue);
    }//GEN-LAST:event_areasMouseExited

    private void transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseClicked
        

    }//GEN-LAST:event_transactionMouseClicked

    private void transactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseEntered
        transaction.setBackground(lightGray);
    }//GEN-LAST:event_transactionMouseEntered

    private void transactionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transactionMouseExited
        transaction.setBackground(lightBlue);
    }//GEN-LAST:event_transactionMouseExited

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        Users go = new Users();
        go.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_usersMouseClicked

    private void usersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseEntered
        users.setBackground(lightGray);
    }//GEN-LAST:event_usersMouseEntered

    private void usersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseExited
        users.setBackground(lightBlue);
    }//GEN-LAST:event_usersMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transactions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transactions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel account;
    private javax.swing.JLabel admin;
    private javax.swing.JLabel admin1;
    private javax.swing.JLabel admin2;
    private javax.swing.JLabel admin3;
    private javax.swing.JLabel admin4;
    private javax.swing.JLabel adminname;
    private javax.swing.JPanel areas;
    private javax.swing.JPanel dashboard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable overview;
    private javax.swing.JPanel paid;
    private javax.swing.JPanel reciept;
    private javax.swing.JPanel refresh;
    private javax.swing.JPanel transaction;
    private javax.swing.JPanel users;
    // End of variables declaration//GEN-END:variables
}
